name: Latest blog post workflow

on:
  push: # Run workflow when commits are pushed
    branches:
      - main # Or the branch you want to monitor

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://raw.githubusercontent.com/Yagasaki7K/website-yagasaki/main/article.xml"
