name: Update README with Latest Blog Posts

on:
  workflow_dispatch:

permissions:
  contents: write # Permissão para escrever no README

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://raw.githubusercontent.com/Yagasaki7K/website-yagasaki/main/article.xml"
